### ISSUE TITLE
Regarding Udacity Dataset 

### ISSUE THREAD

**Issue by ujeshmaurya** [cardwing/Codes-for-autonomous-driving-tasks#2]
[https://github.com/udacity/self-driving-car/tree/master/datasets](url) We also want to use the dataset from the above link. Can you tell us **exactly which dataset you have used from that page**, as there are many links for datasets there?

**Comment by cardwing** [comment]
http://academictorrents.com/userdetails.php?id=5125, dataset 5~8. Please refer to our paper for the dataset division.

**Comment by BuaaAlban** [comment]
> http://academictorrents.com/userdetails.php?id=5125, dataset 5~8. Please refer to our paper for the dataset division.

Hi, do you mean  the fifth to eighth dataset? 
Udacity Dataset 2-3 Compressed 
Udacity Self Driving Car Dataset 3-1: El Camino 
Challenge 2 Train and Test Sets 
Challenges 2 & 3: El Camino Training Data
