### ISSUE TITLE
FMNet Implementation

### ISSUE THREAD

**Issue by azamshoaib** [cardwing/Codes-for-autonomous-driving-tasks#5]
Hi @cardwing 
This is great work. I want to know is it simple 3D ResNet+LSTM or do you provide the FMNet implementation too. Because by looking at 3D-resent-lstm.py I cant find how to incorporate the auxiliary information to your network. Kindly help me in this regard.

**Comment by cardwing** [comment]
You can refer to our paper for more details. Besides, since the feature maps of auxiliary networks are resource-consuming, you'd better first extract them offline and then load the extracted features during the training phase.

**Comment by BuaaAlban** [comment]
> You can refer to our paper for more details. Besides, since the feature maps of auxiliary networks are resource-consuming, you'd better first extract them offline and then load the extracted features during the training phase.

Does this mean that the  implementation in the repo doesn't have auxiliary networks to help training?
